module.exports = {
  MAX_BOAT_AGE_YEARS: 15,
  MIN_FUEL_AMOUNT_LITERS: 20,
  MIN_FUEL_EFFICIENCY: 2.0, // in km/l
  MIN_LIFE_JACKETS_PER_CREW: 1,
  CRITICAL_ENGINE_STATUSES: ['Needs Maintenance', 'Critical'],
  RADIO_COMM_REQUIRED: true,
  WEATHER_CHECK_REQUIRED: true,
  MIN_FUEL_BUFFER_PERCENTAGE: 0.15,
};